version: "3"

services:
  sonarqube_web:
    image: sonarqube:8.5.1-community
    container_name: sonarqube_web
    hostname: sonarqube_web
    ports:
      - 5010:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - "./logs:/opt/sonarqube/logs"
      - "./data:/opt/sonarqube/data"
      - "./extensions:/opt/sonarqube/extensions"

  sonarqube_db:
    image: postgres:13.1
    container_name: sonarqube_db
    hostname: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - pg_db:/var/lib/postgresql
      - pg_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  pg_db:
    driver: local
  pg_data:
    driver: local
